### PR TITLE
Fix key generating function 

### PR DESCRIPTION
**Pull request by RomanovaPrime**
Calling "hashCode" on a Map, returns different output (requestKey) with equal entry (requestOptions.extra). That couses no data to be sent to  FirebasePerformance console, since no one process gets completed. 
Replasing
 " requestKey = options.extra.hashCode; " 
with
" requestKey = options.extra.toString().hashCode; "
in all three places, fixed the issue and the application started send data to the console.

### CODE REVIEW

**Comment by darkxanter** [comment]
If make these changes, for example when we have two concurrent requests we will get the wrong metric for the second request and lose the metric for the first request:
```
onRequest https://pub.dev extra '{}' mapHashCode 824353162 stringHashCode 663241962
onRequest metric hashCode 619894470
onRequest https://pub.dev/packages extra '{}' mapHashCode 411800733 stringHashCode 663241962
onRequest metric hashCode 989305111
onResponse https://pub.dev extra '{}' mapHashCode 824353162 stringHashCode 663241962
onResponse metric hashCode 989305111
onResponse https://pub.dev/packages extra '{}' mapHashCode 411800733 stringHashCode 663241962
onResponse metric hashCode null
```
And as I can see, `hashCode` for `extra` the same in `onRequest` and `onResponse`.
Probably some other interceptor is changing `extra` field in your setup?

**Comment by RomanovaPrime** [comment]
I see. Then the proposed changes will not work in all cases. In our ( case) the 'extra' property does contain some data, witch makes it work with the changed implementation. But, for empty extra data, it won't work properly. 
Our idea was to define an optional property, so users can provide custom function to generate keys (type String), based on RequestOptions. But we decided to make it with as less changes as possible.
However, the extra property might do or not contain data in different projects.

**Comment by darkxanter** [comment]
Try the [feature/change-request-key-generation](/darkxanter/firebase_performance_dio/tree/feature/change-request-key-generation) branch, hope it solves your issue.

**Comment by RomanovaPrime** [comment]
Thank you for the quick reaction!

**Pull request closed without merging**
